ouchbase.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase.c -o ouchbase.lo 
kernel/main.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/exit.lo: /Users/ihor/Development/projects/ouchbase/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/kernel/exit.c -o kernel/exit.lo 
ouchbase/entity.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entity.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entity.zep.c -o ouchbase/entity.lo 
ouchbase/entitymanager.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entitymanager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entitymanager.zep.c -o ouchbase/entitymanager.lo 
ouchbase/entityproxy.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entityproxy.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/entityproxy.zep.c -o ouchbase/entityproxy.lo 
ouchbase/exception/entitylogicexception.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitylogicexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitylogicexception.zep.c -o ouchbase/exception/entitylogicexception.lo 
ouchbase/exception/entitymanagerexception.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitymanagerexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitymanagerexception.zep.c -o ouchbase/exception/entitymanagerexception.lo 
ouchbase/exception/entitymodifiedexception.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitymodifiedexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entitymodifiedexception.zep.c -o ouchbase/exception/entitymodifiedexception.lo 
ouchbase/exception/entityupdatefailedexception.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entityupdatefailedexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/exception/entityupdatefailedexception.zep.c -o ouchbase/exception/entityupdatefailedexception.lo 
ouchbase/identitymap.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/identitymap.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/identitymap.zep.c -o ouchbase/identitymap.lo 
ouchbase/repository.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/repository.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/repository.zep.c -o ouchbase/repository.lo 
ouchbase/unitofwork.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/unitofwork.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/unitofwork.zep.c -o ouchbase/unitofwork.lo 
ouchbase/_etc.lo: /Users/ihor/Development/projects/ouchbase/ext/ouchbase/_etc.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/ihor/Development/projects/ouchbase/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/ihor/Development/projects/ouchbase/ext/ouchbase/_etc.zep.c -o ouchbase/_etc.lo 
$(phplibdir)/ouchbase.la: ./ouchbase.la
	$(LIBTOOL) --mode=install cp ./ouchbase.la $(phplibdir)

./ouchbase.la: $(shared_objects_ouchbase) $(OUCHBASE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ouchbase) $(OUCHBASE_SHARED_LIBADD)

